##
## This code and all components (c) Copyright 2006 - 2025, Wowza Media Systems, LLC. All rights reserved.
## This code is licensed pursuant to the Wowza Public License version 1.0, available at www.wowza.com/legal.
##
name: Wowza Streaming Engine Trial
services:
    trial:
        hostname: wse.docker
        image: wowza/wowza-streaming-engine:latest-trial
        environment:
            - WSE_LICENSE_KEY=$WSE_LICENSE_KEY
            - ADMIN_USER=admin
            - ADMIN_PASSWORD=password
            - IPWHITELIST=*
            - TRANSCODER=enabled #enabled | disabled | remove to not change
            - LOG_LEVEL=WARN #DEBUG INFO WARN ERROR
            - SIMU_LIVE=disabled
        #to persist the configurations between starts of Wowza Streaming Engine, uncomment the lines below:
        # volumes:
        #  - ./wse/applications:/usr/local/WowzaStreamingEngine/applications
        #  - ./wse/conf:/usr/local/WowzaStreamingEngine/conf
        #  - ./wse/content:/usr/local/WowzaStreamingEngine/content
        #  - ./wse/transcoder:/usr/local/WowzaStreamingEngine/transcoder
        ports:
            - 8087:8087
            - 80:80
            - 443:443
            - 1935:1935
    whisper_server:
        hostname: whisper.server
        image: whisper_streaming:local
        platform: linux/arm64
        environment:
            - MODEL=tiny.en # tiny.en, base.en, small.en, medium.en, large-v3
            - REPORT_LANGUAGE=en
            - LOG_LEVEL=INFO
            - MIN_CHUNK_SIZE=1
            # - SOURCE_STREAM=rtmp://wse.docker/live/myStream_160p
        ports:
            - 3000:3000
        volumes:
            - ./model_cache:/tmp

    manager:
        hostname: wsem.docker
        image: wowza/wowza-streaming-engine-manager:latest
        environment:
            - LOG_LEVEL=WARN #DEBUG INFO WARN ERROR
        ports:
            - 8088:8080
